TWITTER_KEY: "nOxesssKhXXcwqlLWVZx7g"
TWITTER_SECRET: "avwlfsHgG26811ukbVDHZCWkuLk7Hem3pYCeJ9U5TE"
OAUTH_TOKEN: "2337109140-MvmjJ7NLH0qNBEniszNeo3X5byrejeUrqEGFB0o"
OAUTH_TOKEN_SECRET: "lk0p9HFvVz7bW2CgM1GHYX0Zrd3IiWtgYPtUyMSxGYdXV"